apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::961747818607:role/UdacityFlaskDeployCBKubectlRole
      username: build   
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::961747818607:role/eksctl-eksctl-demo-nodegroup-ng-a-NodeInstanceRole-18N2H9VABECO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-22T09:51:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1684"
  uid: 0ded2760-82f8-4cbd-b870-15d6f1e9ae45
